project_id = "amzutunyjouejovlrlah"

[functions.create-cellar]
verify_jwt = true

[functions.check-cellar-slug]
verify_jwt = true

[functions.fetch-game-questions]
verify_jwt = true

[functions.weekly-lesson-reset]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.search-cellar-wines]
verify_jwt = true

[functions.create-event]
verify_jwt = true

[functions.get-event-by-slug]
verify_jwt = false